title: Varun Garg
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://www.varungarg.me
baseurl: ""
paginate_path: "blogs/page:num/"
permalink: blogs/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: varungarg2796
   twitter: varungarg2796
   facebook: varungarg2796
   email: varun.garg1@ucdconnect.ie

google_analytics: "UA-58263416-1"
